project:
  type: website

website:
  title: "PHYS170 notes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - about.qmd
      - auto: "lectures/lecture-*.qmd"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



