project:
  type: website
  preview: 
    watch-inputs: true
    navigate: true
    timeout: 300
    port: 8888

website:
  title: "PHYS170 notes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - about.qmd
      - auto: "lectures/lecture-*.qmd"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true





