name: phys170-2023

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10 # pinned by libfmp-1.2.3
  - ipykernel
  - nb_conda_kernels
  - shiny
  - matplotlib
  - numpy
  - scipy
  - nbformat
  - nbclient
  - pip
  - pip:
    - shinylive
    - libfmp      # sound library