---
title: "Lecture 6: Diffraction and Interference"
subtitle: "Chapter 7"
date: "1/24/2023"
format: revealjs
---

## Announcements

::: {.incremental}
- Homework 1 is due tonight at 10pm.  See Canvas for details and the upload page.
- Homework 2 will be posted later today.  It will be due next Tuesday.
- Midterm Exam 1 is next Tuesday!
  - Covers Chapters 1-5
  - Multiple choice and short answer questions
:::

## Daily Quiz
How are the *causes* of diffraction and interference different?

# Interference

## Definition of Interference
Unlike the book, I'm going to discuss interference first because we can then use these ideas to talk about diffraction.

*Interference* is the adding of waves with the same frequency/wavelength.

## Constructive and Destructive Interference

## PhET demo

# Diffraction

## Definition of Diffraction
I'm going to give a different definition of diffraciton than the book, but one that I think makes more sense.

*Diffraction* is the interference of a wave *with itself.*

All of the math we used for interference applies here, too, if we look at the wave in the right way.

## Hugyen's Principle

*Huygens's Principle* is the idea that we can treat each point along a wavefront as its own point source. Looks for the constructive interference of these imaginary point sources let's use determine the shape of the wave as it propagates.

## Diffracion from a slit

## Diffraction from a circular hole

## Next time
Chapter 8: Diffraction and Interference