---
title: "Harmonics Worksheet"
subtitle: "PHYS170 Lecture 7"
date: "1/26/2023"
format:
  pdf:
    papersize: letter
    classoption: 11pt
    geometry: margin=0.75in
    colorlinks: true
---

Here we investigate the idea of Harmonics.  In Part 1 we look at how harmonics are related to wave motion and in Part 2 we see how this motion is related to sound quality.

# Part 1: *Normal Modes*

In this part you'll experiment with a simulation of plucking a guitar or violin string to see how this effects the harmonics generated by the string.

**Be sure to write down answers to all of the questions asked below with the instructions.**

Open the "PhET Normal Modes" simulation.
Use Google to find it or use this URL: <https://phet.colorado.edu/en/simulations/normal-modes> .

## Setup

Follow these steps to load the simulation and learn its features:

1.  Start the simulation itself by clicking on the image.
2.  Choose "One Dimension".  (The "Two Dimension" setting models a square drumhead, but we want a string for now.)
3.  You should see an orange string with 3 blue boxes on it.  You can drag the boxes to make the string move.  Play around with this.
4.  The "Normal Modes" box on the right shows the different harmonics of the string.  "Mode" is another word for "harmonic".  The number of modes used in the simulation is set by the "Number of Masses" box above.  **Change the "Number of Masses" to 9.**  As the number of modes increases and the motion of the string will be smoother.  (We're using 9 because it is the biggest odd number.  That will make some of the experiments below easier.)
5.  The "Normal Modes" box at the bottom shows how much amplitude is in each harmonic.  Use the amplitude sliders to change these values.  How does the motion change?
6.  Click on the pause button on the right (blue circle).  Then click on the "Zero Positions" button.  This resets the simulation.
    -  With the simulation paused you can move the string (drag the blue squares) or the amplitude sliders to change the shape of the string.  Click the "play" button to start the motion again.
    -  Notice that the two sets of settings are dependent on each other: moving the string changes the amplitude sliders and vice versa.

## Experiments and questions

1.  Click "Zero Positions" and press play (if needed).  Set the "Number of Masses" to 9.  Investigate what happens if only one amplitude slider is turned on.
    -  How would you describe the motion of the string in this case?  Are these standing waves, traveling waves, or something else?
    -  Can you identify nodes and antinodes?  Count the number of nodes and antinodes when the following harmonics are turned on (by themselves): 1, 2, 5.
2.  Press "Zero Positions".  Let's pluck the string.  Move the box on the end and watch the resulting wave.  Is this a standing wave, a traveling wave, or something else?  Let the simulation run for a few seconds, then observe the wave motion again.  How has it changed?  How would you describe the values of the amplitudes?  In other words, what is the general pattern of the amplitudes?  **Write down the amplitude numbers because you will use them in Part 2 below.**  
3.  Press "Zero Positions".  Now "pluck" the string in the center.  Describe the motion of the string.  Now, look at the mode amplitudes.  What pattern do you see here?  **Write down the amplitude numbers because you will use them in Part 2 below.**
4.  With the last two experiments in mind, why does a guitar or violin sound different when you pluck/bow it in the center instead of near the end?
5.  "Zero positions" again.  Move the amplitude sliders to turn on several of the odd-numbered modes.  Can you make a general statement about the shape of the waves when only odd modes are present?  Repeat with only even-numbered modes.  What does the mode shape look like for even modes?

# Part 2: *Making Waves*

In this part we'll take the idea of normal modes and investigate how this changes the sound.

Open the "PhET Fourier: Making Waves" simulation.  Google it or use this URL: <https://phet.colorado.edu/en/simulations/fourier-making-waves>.  This simulation uses sound, so check the volume on your device and/or use headphones.

## Setup

1.  Click the image to start the simulation.  Pick the "Discrete" page.
2.  At the top of the page are mode amplitude sliders like we saw in the "Normal Modes" simulation.  The "Harmonics" graph shows the wave for each of the harmonic functions, each one with a different color.  The "Sum" graph adds all of the "Harmonics" curves to get the resulting waveform. Try adjusting the amplitude sliders to see how these graphs change (or you can click on the numbers to type in the values).  You can click on the +/- buttons beside each graph to zoom the horizontal axis.

## Experiments

1.  First, let's see what frequencies/pitches are represented by these sliders.  If you have a tuner app on your phone, open that.  (If not, we'll share the answers as a class.)  Go one-by-one through each of the amplitude sliders, turn it on, and use the tuner app to measure the frequency.  What is the mathematical relationship between the frequencies here?
2.  Click on the checkbox on the right side by the music note to turn on the sound.  Play with the amplitude sliders.  How does the sound change as you adjust the sliders?
3.  The "Waveform" combo box in the top right has several preset wave shapes.  Listen to these.  How does the *timbre* or tone quality of the sound relate to the wave shape?  Which of these preset shapes sounds most like a flute? an oboe?
4.  Look at the amplitude values that you wrote down in Questions 3 and 4 of Part 1.  Enter these values into the this simulation and listen.  What is the difference in sound between plucking the string in the center and plucking it near the end?

## Bonus experiments (if time allows)
Although we've focussed on the wave shape and how it would effect the timbre of an individual instrument, we can also start to think about pitch and harmony.  We'll discuss this in detail later in the semester, but the tools here will give you a preview of where we are going.

1.  Use the tuner app to measure the musical *pitches* of each of the harmonics.  In our class we'll typically describe pitches as a letter and number, with the number indicating the octave.  The usual naming convention has C~4~ as middle C on a piano staff, which has a frequency of about 262 Hz. (The octaves start at C for numbering purposes).
2.  How would you describe the arrangement of the pitches as you go from the first harmonic (amplitude A~1~ on the simulation) to the higher ones?
3.  Identify the harmonic that is one octave above the first harmonic (by sound, or however you can).  What is the mathematical relationship between the frequencies of these two harmonics?  Which harmonics correspond to the next two higher octaves of the fundamental?
4.  Turn on the 2nd and 3rd harmonics only.  What is the musical description of these two frequencies played together?
5.  Now do 4, 5, and 6 together.  What is this combination, musically?
6.  Is it possible to build a minor triad using this simulation?  Why or why not?