---
title: "Group Project Description"
subtitle: "PHYS170"
date: "2/16/2023"
format:
  pdf:
    papersize: letter
    classoption: 11pt
    geometry: margin=0.75in
    colorlinks: true
---

The document contains the basic outlines of the Group Project.  Details will be added as the semester progresses.

## Group Assignments
- **Group 1:** Melissa, Katy, Ava, Andrew
- **Group 2:** Nick, Ty, Maxwell, Ronin
- **Group 3:** Toops, Charlie, Thomas, Mark

## Project grading scheme
150 points total (25% of course grade).

::: {style="font-size:80%"}
- **(50 pts) Planning steps**
  - (25 pts) Initial plan (Feb. 24)
  - (25 pts) Midway progress report (March 17)
- **(50 pts) Final written report**
  - (15 pts) Rough draft (March 24)
  - (25 pts) Final report (April 14)
  - (10 pts) Individual reflection (April 14)
- **(50 pts) Final oral presentation** (April 28)
  - (10 pts) Demonstration of the instrument
  - (20 pts) Presentation content
  - (20 pts) Presentation delivery
:::

## Initial plan
Due before Spring Break (Feb. 24, 10pm) on Canvas

- What is the instrument?
- What is each person's role? (See next slide)
- How are you going to communicate with each other?
- When are you going to meet to work on this?
- How are you dividing the work among the group members?
- How are you going to store and share your work with each other?

## Group Roles
As part of the initial plan, each role below must be assigned to one group member.

::: {style="font-size:80%"}
- **Manager/Facilitator:** Manages the group by helping to ensure that the group stays on task, is focused, and that everyone participates.  Organizes meetings and sends communications to the group.  Responsible for submitting reports using Canvas.
- **Recorder/Archivist:** Keeps notes about the group's work and shares them with the group.  Takes primary role in the written reports; may delegate writing work to others.
- **Spokesperson/Presenter**: Will MC the final presentation (but everyone must help present). The Spokesperson should rely on the recorder’s notes to guide their report.  Also responsible for communicating with Dr. C as issues arise.
- **Questioner/Strategy Analyst/Technical Analyst**: Focusses on the big picture.  Ensures everyone's ideas being incorporated. Plays "Devil's Advocate" in discussions.  Takes the lead in technical discussions.
:::

## Requirements for the instrument

- Must be a tonal instrument (produces well-defined pitches)
- Must play multiple pitches in a controlled way
  - At least an octave of a pentatonic scale (e.g. C D E G A C)
- You must build it yourselves
- You must be able to explain how it works
- Purely electronic instruments are not acceptable (e.g. a synth would be out, but an electric guitar is okay)

## Final report contents
More details will follow

- Description of the instrument and how you built it
- Description of how the instrument produces sound (e.g. what is vibrating?)
- What determines the fundamental frequency
- Description of how one plays the instrument
  -  How do you change the pitch?  The intensity?  Can you sustain notes?
- Frequency analysis (spectrum)

The midway report (3/17) will contain initial results on all of these topics.

Rough draft of the complete final report is due 3/24.

## Final presentation
More details will follow

- Summary of the items in the written report
- Demonstration of the instrument and how it is played
  - Show how to change pitch/intensity/sustain (if applicable)
  - Play a simple melody of your choosing
